export const FETCH_BOOKS = 'FETCH_BOOKS'

export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE'
export const ADD_BOOK_STARTED = 'ADD_BOOK_STARTED'

export const BOOK_SELECTION = 'BOOK_SELECTION'